name: 'Changelog Release Agent'
description: 'Drive semantic versioned releases from the changelog file.'
inputs:
  changelog:
    description: 'The changelog file to examine.'
    required: false
    default: 'CHANGELOG.md'
  meson-wrap:
    description: 'If set to true a meson wrap file is included in the release.'
    required: false
    default: 'false'
  meson-library-provided:
    description: 'Only used if meson-wrap is to true.  If defined sets the output meson dependency name.'
    required: false
    default: 'none'
runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/release.sh \
          ${{ github.repository }} \
          ${{ inputs.changelog }} \
          ${{ inputs.meson-wrap }} \
          ${{ inputs.meson-library-provided }} \
      shell: bash
